import { StyleSheet } from 'react-native';
import { BW } from './theme';

export const getGeneralStyle = (colors: any) =>
  StyleSheet.create({
    appContainer: {
      flex: 1,
      backgroundColor: 'transparent',
      height: '100%',
    },

    container: {
      flex: 1,
      backgroundColor: 'transparent',
    },
    form: {
      padding: 10 * BW(),
      paddingHorizontal: 30 * BW(),
    },
    btnSubmit: {
      backgroundColor: colors.primary,
      height: 'auto',
      paddingVertical: 8 * BW(),
      minHeight: 45 * BW(),
      paddingHorizontal: 40 * BW(),
      width: '100%',
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      marginVertical: 10 * BW(),
      marginTop: 30 * BW(),
    },
    emailStyle: {
      width: '100%',
    },
    passStyle: {
      marginTop: 0 * BW(),
      flex: 1,
    },
    styleInput: {
      backgroundColor: colors.background,
      width: '100%',
      paddingVertical: 10 * BW(),
      paddingHorizontal: 10 * BW(),
      marginTop: 8 * BW(),
      borderRadius: 8 * BW(),
      borderWidth: 0.6 * BW(),
    },
    stylePassInput: {
      backgroundColor: colors.background,
      width: '100%',
      paddingVertical: 10 * BW(),
      paddingHorizontal: 10 * BW(),
      marginTop: 0 * BW(),
      borderRadius: 8 * BW(),
      borderColor: colors.gray + '88',
      borderWidth: 0 * BW(),
      borderBottomWidth: 0.4 * BW(),
    },
    styleText: {
      color: colors.text,
    },
    containerBackStyle: {
      right: 10 * BW(),
      position: 'absolute',
      zIndex: 99,
      top: 10 * BW(),
    },
    backStyle: {
      width: 'auto',
      height: 'auto',
      backgroundColor: 'rgba(0,0,0,0.07)',
      zIndex: 99,
      padding: 5 * BW(),
      borderRadius: 44 * BW(),
    },
    styleIconBack: {
      tintColor: colors.primary,
      width: 20 * BW(),
      height: 20 * BW(),
    },
    passShow: {
      width: 'auto',
      height: 'auto',
      backgroundColor: colors.background,
      borderRadius: 8 * BW(),
      marginTop: 2 * BW(),
      padding: 0,
      right: 5 * BW(),
    },
    styleIconEye: {
      tintColor: colors.primary + '99',
      width: '70%',
      height: '70%',
    },
    forgetPass: {
      width: 'auto',
      height: 'auto',
      padding: 0,
      backgroundColor: 'transparent',
      alignItems: 'flex-start',
      alignSelf: 'flex-start',
      marginTop: 8 * BW(),
    },
    signUp: {
      width: 'auto',
      height: 'auto',
      padding: 0,
      backgroundColor: 'transparent',
      alignItems: 'flex-start',
      alignSelf: 'flex-start',
      marginLeft: 8 * BW(),
    },
    uaePass: {
      width: '100%',
      height: 'auto',
      padding: 0,
      backgroundColor: 'transparent',
      marginTop: 8 * BW(),
      marginBottom: 8 * BW(),
    },
    uaePassIcon: {
      width: '100%',
      height: 48 * BW(),
    },
    halfLine: {
      flex: 2,
      borderWidth: 1 * BW(),
      borderColor: colors.primary + '88',
      height: 0,
    },
    or: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 12 * BW(),
    },
    guest: {
      alignSelf: 'center',
      height: 'auto',
      borderWidth: 1 * BW(),
      width: '100%',
      paddingVertical: 8 * BW(),
      paddingHorizontal: 10 * BW(),
      marginTop: 12 * BW(),
      borderRadius: 20 * BW(),
      borderColor: colors.primary,
      backgroundColor: 'transparent',
      alignItems: 'center',
      marginVertical: 8 * BW(),
    },
    logoContainer: {
      alignItems: 'center',
      width: 300 * BW(),
      justifyContent: 'center',
      alignSelf: 'center',
      marginTop: 50 * BW(),
    },
    error: {
      color: '#db2c43',
    },
    currencyImage: {
      width: 12 * BW(),
      height: 12 * BW(),
      resizeMode: 'contain',
      tintColor: '#000',
    },
  });
